## Arrays
Diferentemente de listas, arrays só podem conter o mesmo tipo de dado. \
Outra particularidade importante é que Python permite a criação de arrays multidimensionais. Um array bidimensional é o que chamamos de matriz, mas é possível criar um array de múltiplas dimensões.

Para manipular arrays temos que importar o pacote numpy. \
A forma mais simples de criar um array em Python é criar uma lista e transformá-la num array.

In [1]:
import numpy as np
a = [1,2,3]
type(a)

list

In [2]:
b = np.array(a)
b

array([1, 2, 3])

In [3]:
type(b)

numpy.ndarray

Da mesma forma que criamos uma lista com o método range, podemos criar um array com o método arange. \
Vamos criar um array contendo os elementos 0, 1, ... 9.

In [4]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Outra alternativa para criar um array é usar o método linspace. Este método requer 3 argumentos: o número inicial, o número final e a quantidade de números no intervalo entre o número inicial e final, incluindo ambos. \
Vamos gerar um array de 0 a 3 com 31 itens e depois outro array de 0 a 30 com 31 itens

In [5]:
np.linspace(0,3,31)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5,
       2.6, 2.7, 2.8, 2.9, 3. ])

In [6]:
np.linspace(0,30,31)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25.,
       26., 27., 28., 29., 30.])

Como criar um array bidimensional (matriz)? \
A forma mais simples envolve criar uma lista contendo duas listas e transformar essa lista num array.

In [7]:
c = [[1,2,3],[10,20,30]]
np.array(c)

array([[ 1,  2,  3],
       [10, 20, 30]])

Em alguns casos pode ser útil criar matrizes contendo apenas zeros ou apenas uns. \
Vamos criar uma matriz 3x4 contendo apenas zeros e uma matriz 4x3 contendo apenas uns. \
Importante: a dimensão da matriz tem que ser passada como uma tupla, ou seja, 3x4 tem que ser representado por (3, 4).

In [8]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [9]:
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

Agora vamos criar uma matriz com 3 linhas e 10 colunas contendo os números de 0 a 29, dessa forma: \
0  ...  9 \
10 ... 19 \
20 ... 29

Inicialmente vamos usar o método linspace para gerar um array unidimensional contendo todos os números.

In [10]:
nim30 = np.linspace(0,29,30)

In [11]:
nim30.shape

(30,)

O que temos que fazer agora é mudar o formato desse vetor. Para isso usamos o método reshape.

In [12]:
nim30.reshape(3,10)

array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14., 15., 16., 17., 18., 19.],
       [20., 21., 22., 23., 24., 25., 26., 27., 28., 29.]])

Exercício 1 \
Crie um array usando linspace() que contenha valores de -3.0 até +3.0 em intervalos de 0.1

In [19]:
np.linspace(-3, 3, 61)

array([-3. , -2.9, -2.8, -2.7, -2.6, -2.5, -2.4, -2.3, -2.2, -2.1, -2. ,
       -1.9, -1.8, -1.7, -1.6, -1.5, -1.4, -1.3, -1.2, -1.1, -1. , -0.9,
       -0.8, -0.7, -0.6, -0.5, -0.4, -0.3, -0.2, -0.1,  0. ,  0.1,  0.2,
        0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ,  1.1,  1.2,  1.3,
        1.4,  1.5,  1.6,  1.7,  1.8,  1.9,  2. ,  2.1,  2.2,  2.3,  2.4,
        2.5,  2.6,  2.7,  2.8,  2.9,  3. ])

Exercício 2 \
Crie um array unidimensional de 1 a 10 e depois transforme esse vetor numa matriz 2x5.


In [21]:
arr = np.arange(1,11)
arr.reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

Exercício 3 \
Gere uma matriz de zeros, contendo n linhas por m colunas, sendo n e m informados pelo usuário.

In [22]:
n = input("Digite o valor de N.")
m = input("Digite o valor de M.")
n = int(n)
m = int(m)
np.zeros((n,m))

Digite o valor de N.10
Digite o valor de M.20


array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.]])