## Operações com Arrays
Podemos operar com diversos (ou todos) elementos de um array numa única operação. \
Suponha que tenhamos o array 0..9 e queremos somar 10 a todos os elementos do array. É possível fazer essa operação sem usar um laço? Em Python, sim!

In [5]:
import numpy as np

In [16]:
arr = np.arange(0,10)

In [17]:
arr + 10

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

Se fizermos arr1 - 10 teremos o vetor original?

In [18]:
arr - 10

array([-10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1])

Vamos agora criar outro array (arr2), contendo os elementos 10..19. \
Assim como somamos um inteiro aos elementos de um array, podemos somar dois arrays. \
Vejamos o resultado de arr1 + arr2:

In [9]:
arr2 = np.arange(10,20)

In [19]:
arr + arr2

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

Para alterar um elemento do array, basta indicar o índice desse elemento. \
Ex: alterar o primeiro elemento de arr1, colocando 10 no lugar de 0.

In [12]:
arr[0] = 10
arr

[10, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

E se quisermos alterar todos os elementos do array, colocando 10 em todas as posições?

In [37]:
arr[:] = 10
arr

array([10, 10, 10, 10, 10, 10, 10, 10, 10, 10])

Exercício 1 \
Altere os 5 primeiros elementos de arr1, colocando o valor 20.

In [38]:
arr[:5] = 20
arr

array([20, 20, 20, 20, 20, 10, 10, 10, 10, 10])

Exercício 2 \
Altere os 3 últimos elementos de arr1, colocando o valor 30.

In [39]:
arr[(len(arr) - 3):] = 30
arr

array([20, 20, 20, 20, 20, 10, 10, 30, 30, 30])

Vamos agora criar um novo array (arr3), utilizando os 5 primeiros elementos de arr2.

In [43]:
arr3 = arr2[:5]
arr3

array([10, 11, 12, 13, 14])

A seguir, vamos colocar 0 em todos os elementos de arr3 e observar o que acontece com arr2.

In [44]:
arr3[:] = 0
arr2

array([ 0,  0,  0,  0,  0, 15, 16, 17, 18, 19])

O que aconteceu foi que arr3 não foi criado com novos valores. Este array "aponta" para os 5 primeiros valores de arr2. Assim, ao alterar os elementos de arr3, alteramos também os 5 primeiros elementos de arr2.

A função reshape do numpy permite mesclar 2 arrays. Veremos a seguir como fazer isso.

In [51]:
arr4 = np.array([[1,2,3], [4,5,6]])
arr4.reshape(-1)

array([1, 2, 3, 4, 5, 6])